language: haskell

ghc:
  - 7.4
  - 7.6

notifications:
  email: false

install:
  cabal install --enable-tests --enable-benchmark --force-reinstalls --only-dependencies

script:
  cabal configure --enable-tests --enable-benchmark && cabal build && cabal test