language: haskell

notifications:
  email: false

install: cabal install --enable-tests --enable-benchmark --force-reinstalls --only-dependencies

script: cabal configure --enable-tests --enable-benchmark && cabal build && cabal test